name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'apps/docs-website/**'
      - 'packages/core/**'
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - 'apps/docs-website/**'
      - 'packages/core/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
          check-latest: true
          pnpm-version: 10.33.3
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build core package
        run: pnpm --filter @f-vueuse/core build

      - name: Build docs
        run: pnpm --filter docs-website build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/docs-website/.vitepress/dist
          publish_branch: gh-pages
